linters-settings:
  gci:
    sections:
      - standard
      - default
      - Prefix(github.com/juju/juju)
    skip-generated: true
  gofmt:
    simplify: true
  govet:
    disable-all: true
    enable:
      - asmdecl
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
# TODO(4.0): re-enable me
#      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  revive:
    rules:
      - name: unexported-naming
        severity: error
        disabled: false
      - name: exported
        severity: error
        disabled: false
        arguments:
          - "disableStutteringCheck"
          - "sayRepetitiveInsteadOfStutters"
      - name: atomic
        severity: error
        disabled: false
      - name: defer
        severity: error
        disabled: false
        arguments:
          - [ "return", "recover", "method-call" ]
linters:
  disable-all: true
  enable:
    - gci
    - govet
    - gofmt
    - ineffassign
    - misspell
    - unconvert
    - unused
    - sqlclosecheck
    - revive
run:
  timeout: 30m
  modules-download-mode: readonly
skip-dirs:
  - _deps
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
