linters-settings:
  gci:
    sections:
      - standard
      - default
      - Prefix(github.com/juju/juju)
    skip-generated: true
  gofmt:
    simplify: true
  govet:
    disable-all: true
    enable:
      - asmdecl
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
linters:
  disable-all: true
  enable:
    - gci
    - govet
    - gofmt
    - ineffassign
    - misspell
    - unconvert
    - exportloopref
    - unused
    - sqlclosecheck
run:
  timeout: 30m
  modules-download-mode: readonly
skip-dirs:
  - acceptancetests
  - _deps
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
