version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - errcheck
  settings:
    errcheck:
      check-type-assertions: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _deps
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
