version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
  settings:
    govet:
      enable:
        - asmdecl
        - assign
        - atomic
        - bools
        - buildtag
        - copylocks
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - shift
        - stdmethods
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
      disable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _deps
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - Prefix(github.com/juju/juju)
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
