options:
  string-option:
    type: string
    default: "Default Value"
    description: "A short description of the configuration option"
  boolean-option:
    type: boolean
    default: False
    description: "A short description of the configuration option"
  int-option:
    type: int
    default: 9001
    description: "A short description of the configuration option"
  another-string-option:
    type: string
    default: "Another default value"
    description: "A short description of the configuration option"
