options:
  strnildefault:
    default:
    description: A string setting for charm with nil default value.
    type: string
  stremptydefault:
    default: ""
    description: A string settings for charm with empty default value.
    type: string
  intnildefault:
    default:
    description: An int setting for charm with nil default value.
    type: int
  floatnildefault:
    default:
    description: A float setting for charm with nil default value.
    type: float
  booleannildefault:
    default:
    description: A boolean setting for charm with nil default value.
    type: boolean