options:
  hexstring:
    default: "0xD06F00D"
    description: A hex string that should be a string, not a number.
    type: string
  numberstring:
    default: "123456"
    description: A string that happens to contain a number.
    type: string
  nonoctal:
    default: "01182252"
    description: TODO remove the quotes. Number that isn't valid octal, so should be a string.
    type: string
