# Copyright 2020 juju-qa@canonical.com
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  thing:
    default: üéÅ
    description: A thing used by the charm.
    type: string
  status:
    default: "hello"
    description: temporary string for unit status
    type: string
  thing2:
    default: ""
    description: an option to set
    type: string
