name: starsay
summary: A dumb little test charm for resources.
maintainer: Nate Finch <nate.finch@gmail.com>
description: Doesn't do anything at all.
series:
  - kubernetes
tags:
  - application
provides:
  admin:
    interface: http
resources:
  store-resource:
    type: file
    filename: filename.tgz
    description: One line that is useful when operators need to push it.
  install-resource:
    type: file
    filename: gotta-have-it.txt
    description: get things started
  upload-resource:
    type: file
    filename: somename.xml
    description: Who uses xml anymore?
