name: "Snapcraft"
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  snap:
    name: Build linux-arm64
    runs-on: [self-hosted, linux, arm64, aws, quad-xlarge]

    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo snap install snapcraft --classic
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup LXD
        uses: canonical/setup-lxd@4e959f8e0d9c5feb27d44c5e4d9a330a782edee0

      - name: Wait for LXD
        run: |
          while ! ip link show lxdbr0; do
            echo "Waiting for lxdbr0..."
            sleep 10
          done

      - name: Set up Go
        if: env.RUN_TEST == 'RUN'
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Build snap
        shell: bash
        run: |
          set -euxo pipefail
          snapcraft --use-lxd

      - name: Install snap
        shell: bash
        run: |
          set -euxo pipefail
          sudo snap install *.snap --dangerous
          # Since we're installing dangerously, we need to
          # manually grant permissions to juju
          sudo snap connect juju:lxd lxd
          sudo snap connect juju:config-lxd
          sudo snap connect juju:dot-local-share-juju
          sudo snap connect juju:ssh-keys
          snap connections juju

      - name: Test bootstrap
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p ~/.ssh
          juju bootstrap --model-default enable-os-upgrade=false localhost --debug
