name: "Update homebrew tap"
on:
  release:
    types: [published]
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-brew-tap:
    permissions:
      contents: none
    if: github.repository_owner == 'juju'
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@c5ddc585e75f0f750a8b4f610688b4bec9e80915 # master
        with:
          token: "${{ secrets.TOKEN }}"
          formula: juju
          livecheck: true
